helm/templates/clusterrolebindings.yaml
helm/templates/operator.yaml
helm/templates/rolebindings.yaml
helm/templates/roles.yaml
helm/templates/serviceaccount.yaml
helm/templates/services.yaml

change the namespace kubesphere-monitoring-system to Release.Namespace.

change the namespace  to Release.Namespace

---

README.md
config/bundle.yaml
config/manager/kustomization.yaml
config/manager/manager.yaml
config/samples/bundle.yaml
config/samples/notification_v1alpha1_notificationmanager.yaml

change image tag from latest to v0.1.0

change image tag from latest to v0.1.0

---

README.md

Signed-off-by: Benjamin <benjamin@yunify.com>

Add global receiver and default config desc

---

config/bundle.yaml
config/crd/bases/notification.kubesphere.io_slackreceivers.yaml
config/crd/bases/notification.kubesphere.io_wechatreceivers.yaml
helm/crds/slackreceivers.yaml
helm/crds/wechatreceivers.yaml
pkg/apis/v1alpha1/slackreceiver_types.go
pkg/apis/v1alpha1/wechatreceiver_types.go

fix the bug config selector can not be null

fix the bug config selector can not be null

---

cmd/notification-manager/main.go
config/bundle.yaml
config/manager/manager.yaml
helm/templates/operator.yaml
pkg/controllers/notificationmanager_controller.go

add host local time to container

---

pkg/notify/config/config.go

fix receiver can not use default config when config selector is nil

---

pkg/controllers/notificationmanager_controller.go

Comment errors abouting the service and deployment of nitificationManager

change SetupWithManager notes

---

Makefile
cmd/notification-manager/Dockerfile
cmd/operator/Dockerfile

build image for arm64

---

helm/values.yaml

change pullPolicy to IfNotPresent

---

adapter/sink/README.md
adapter/sink/cmd/main.go

add department to the notifications

---

pkg/apis/v2alpha1/groupversion_info.go
pkg/notify/notifier/webhook/webhook.go
pkg/notify/notifier/wechat/wechat.go

1. fix bug notification manager operator crash
2. webhook receiver can have a nil config

fix some bug

---

config/samples/bundle.yaml
config/samples/global_receiver.yaml
pkg/notify/config/config.go

fix bug notification manager crash when crd annotations is nil

---

README.md
adapter/sink/Makefile
adapter/sink/cmd/main.go
adapter/sink/cmd/types.go
adapter/sink/test/alert.json
config/bundle.yaml
config/crd/bases/notification.kubesphere.io_configs.yaml
config/crd/bases/notification.kubesphere.io_receivers.yaml
config/samples/bundle.yaml
config/samples/template.yaml
config/update/update.sh
helm/Chart.yaml
helm/crds/notification.kubesphere.io_configs.yaml
helm/crds/notification.kubesphere.io_receivers.yaml
helm/templates/template.yaml
helm/values.yaml
pkg/apis/v2beta1/notificationmanager_types.go
pkg/notify/notifier/dingtalk/dingtalk.go
pkg/notify/notifier/slack/slack.go
pkg/notify/notifier/wechat/wechat.go

Add the update script, it can update the old crds to the newest.
Fix some bugs.

add update script

---

config/samples/bundle.yaml
config/samples/notification_manager.yaml

Fix a spelling error

---

README.md
config/samples/bundle.yaml
config/samples/notification_manager.yaml
helm/values.yaml
pkg/controllers/notificationmanager_controller.go

update the default release version to v1.0.0

---

config/bundle.yaml
config/crd/bases/notification.kubesphere.io_configs.yaml
config/default/manager_auth_proxy_patch.yaml
helm/crds/notification.kubesphere.io_configs.yaml
helm/values.yaml
pkg/apis/v2beta1/config_types.go
pkg/apis/v2beta1/notificationmanager_types.go
pkg/apis/v2beta1/receiver_types.go

update kube-rbac-proxy to v0.8.0

---

docs/proposals/Integrate-SMS-Service-Crd-For-Notification-Manager.md

/kind feature
/cc @benjaminhuo @wanjunlei

Proposal: Integrate SMS Service Crd For Notification-Manager

---

config/bundle.yaml
config/crd/bases/notification.kubesphere.io_notificationmanagers.yaml
go.mod
go.sum
helm/crds/notification.kubesphere.io_notificationmanagers.yaml

Signed-off-by: zhu733756 <talonzhu@yunify.com>
- fix go packages incompatible.
- make test and regenerate crds.

fix go packages incompatible

---

cmd/notification-manager/Dockerfile
cmd/operator/Dockerfile
config/bundle.yaml

fix bug arm64 image running error

---

pkg/controllers/notificationmanager_controller.go
pkg/notify/notifier/dingtalk/dingtalk.go
pkg/notify/notifier/email/email.go
pkg/notify/notifier/slack/slack.go
pkg/notify/notifier/sms/sms.go
pkg/notify/notifier/template.go
pkg/notify/notifier/webhook/webhook.go
pkg/notify/notifier/wechat/wechat.go
pkg/utils/utils.go
pkg/webhook/v1/handler.go
pkg/webhook/webhook.go

add an api to send notifications directly

---

README.md
docs/api/_index.md
pkg/webhook/v1/handler.go
pkg/webhook/webhook.go

add api documentation

---

README.md

Signed-off-by: Benjamin <benjamin@yunify.com>

Adjust alertmanager integration guide

---

Makefile
config/bundle.yaml
config/manager/kustomization.yaml
config/samples/bundle.yaml
config/samples/notification_manager.yaml
go.mod
pkg/apis/v2beta2/receiver_types.go
pkg/apis/v2beta2/receiver_webhook.go

change image repository from kubespheredev to kubesphere

---

pkg/controllers/notificationmanager_controller.go

Modify the permission of the mounted hostpath to read-only

---

CHANGLOG.md

Signed-off-by: zhu733756 <talonzhu@yunify.com>
- reorder and adjust hostpath CHANGLOG.md

reorder and adjust hostpath CHANGLOG.md

---

adapter/pkg/export/stdout/types.go
pkg/notify/config/config.go
sidecar/kubernetes/Dockerfile
sidecar/kubernetes/Makefile
sidecar/kubernetes/README.md
sidecar/kubesphere/3.1.0/Dockerfile
sidecar/kubesphere/3.1.0/Makefile
sidecar/kubesphere/3.1.0/README.md

fix bug does not send notification history when ns is nil

---

pkg/notify/notifier/dingtalk/dingtalk.go
pkg/notify/notifier/wechat/wechat.go

fix bug the error was not returned to the caller

---

VERSION
config/bundle.yaml
config/manager/kustomization.yaml

init 1.4.0

---

.github/workflows/push-nm-image.yaml
.github/workflows/push-operator-image.yaml
Makefile

This PR is used to automatically build and push relevant images.
Signed-off-by: chengdehao <wenchajun@gmail.com>

add the ci build

---

pkg/constants/constants.go
pkg/controller/controller.go
pkg/webhook/v1/handler.go

Support to get kubesphere cluster name from configmap

---

CHANGLOG.md
README.md
RELEASE.md
controllers/notificationmanager_controller.go
helm/values.yaml

Preparations for the release of v2.0.0

---

README.md
helm/templates/notificationmanagers.yaml

fix helm install error

---

pkg/dispatcher/dispatcher.go

fix: code error

---

CHANGLOG.md
README.md
RELEASE.md
helm/values.yaml

init v2.0.1

---

pkg/template/template.go

Fix bug must use full name when setting Feishu template

---

config/i18n/zh-cn.yaml
config/samples/bundle.yaml
config/samples/template.yaml
docs/crds/receiver.md
helm/templates/template.yaml
helm/values.yaml
pkg/template/template.go
pkg/template/types.go
test/testdata/alert-auditing.json

fix some bugs

---

CHANGLOG.md
README.md
RELEASE.md
helm/Chart.yaml
helm/values.yaml

release v2.1.0

---

.github/workflows/main.yaml

Signed-off-by: Gentleelephant <birdhk@kubesphere.io>
fix: #183

Optimize CI

---

CHANGLOG.md
README.md
RELEASE.md
helm/Chart.yaml
helm/values.yaml

Signed-off-by: Gentleelephant <birdhk@kubesphere.io>

release v2.2.0

---

config/bundle.yaml
config/default/manager_auth_proxy_patch.yaml
helm/values.yaml

Signed-off-by: Gentleelephant <birdhk@kubesphere.io>

Update kube-rbac-proxy to 0.11.0 #186

---

CHANGLOG.md
config/bundle.yaml
config/default/manager_auth_proxy_patch.yaml
helm/values.yaml

Signed-off-by: Gentleelephant <birdhk@kubesphere.io>

Update kube-rbac-proxy to 0.11.0 

---

config/samples/template.yaml
pkg/apis/v2beta2/common.go
pkg/controller/controller.go

- Add a html template
- Support getting cluster name from annotation

add a html tepmlate

---

docs/crds/silence.md

Fix Typo in documentation

---

pkg/webhook/v1/handler.go

add alerttime to metric alert
